### ISSUE TITLE
macOS 10.14 Support

### ISSUE THREAD

**Issue by WorkInProgress-Development** [Bunn/UTMBeGone#2]
Hello!
The program looks to be very, very useful for me, but I am still running mostly on 10.14 (Mojave). Unfortunately due to another project I don't have the 10.14 SDK to test it with, and the App Store version requires 10.15. Could it be recompiled for 10.14, or is it using features only available for 10.15?

Thank you.

**Comment by UnderEu** [comment]
@Bunn contacted me and I tested it on 10.14.6 - update is online at the MAS and should be available here anytime soon.

**Comment by Bunn** [comment]
The App Store version now supports 10.14
