### ISSUE TITLE
app is messing up copy/paste of `&nbsp;` in editor

### ISSUE THREAD

**Issue by doekman** [Bunn/UTMBeGone#3]
When I want to copy/paste the text `&nbsp;` in TextMate, it pastes `&nbsp%3B`. When I quit the app, and I try again, pasting works as expected.

Also: perhaps a link in the preference-dialog to some web-page? Now the app is a bit incognito (I forgot I installed it via the AppStore).

**Comment by Bunn** [comment]
Thanks for the report. I'll take a look at this. 
And yep, good suggestion for the link to the project page. Thanks.

**Comment by Bunn** [comment]
@doekman This is fixed and live on the App Store ( https://apps.apple.com/us/app/utmbegone/id1530867730?mt=12 )
Thanks again for the report :)
