### ISSUE TITLE
Cleaning facebook links

### ISSUE THREAD

**Issue by gklka** [Bunn/UTMBeGone#6]
I have a trouble with cleaning parameters from facebook post links like:

```https://www.facebook.com/Turistamagazin/posts/2837045049731958?__cft__[0]=AZUyls5I3kvF_GJ929Yr0ES2TV63UdUlD-RXNPqTBP-5OnrGNYXl8ed6OhkHjhay2Fc3ifOF95-dFpEA8nzCnih_5z0a1pGUlEntgY0r8oMKoK7lN7RAhl-r2fpQAwILPlYvcJZmxw6g7vwpZENA9UAFhJuXg5WQOwvMlq0QQwF2qCwbPY7XSkwc8VleeeuA1elwfOG0oNG3_b2x6DXmal4SrR-M8C0f1SbWzDBZUKp85w&__tn__=%2CO%2CP-R```

I added `__cft__[0]` and `__tn__` to the query items list, but it seems the app is not able to cut them.

![Screen Shot 2020-10-08 at 12 16 42](https://user-images.githubusercontent.com/866694/95446294-615e1c00-0960-11eb-93e2-56139e3c7a0b.png)

**Comment by Bunn** [comment]
fixed on https://github.com/Bunn/UTMBeGone/releases/tag/1.3.0

**Comment by gklka** [comment]
Works fine, thank you!
