### ISSUE TITLE
App name is not easily discoverable

### ISSUE THREAD

**Issue by doekman** [Bunn/UTMBeGone#7]
If you don't know the name of UTMBeGone (or just can't remember it quickly), the only way to determine the name is by selecting the menu item `Project Website`.

While this is fine, it could be done a bit more elegant, by adding the project-website as a clickable link on the preference-window. And while you are at it, rename the title of the window to `Preferences` or `UTMBeGone Preferences`. There's room! As added bonus, the menu becomes shorter!

![image](https://user-images.githubusercontent.com/1086388/95598417-2dfaba80-0a50-11eb-8fce-b243417792d9.png)

(just my two cents)

**Comment by Bunn** [comment]
Fixed on https://github.com/Bunn/UTMBeGone/releases/tag/1.3.0
